### ISSUE TITLE
Peak position of expected peaks not shown. 

### ISSUE THREAD

**Issue by RLumSK** [crp2a/gamma#29]
**Describe the bug**

The plot method for the `PeakPosition-class` seems to always just return the observed peak positions and not the expected peak positions. This might be correct, but then I would expect that the calibration is applied automatically when plotting. This is not the case. We can use the vignette example to reproduce the issue: 

**To Reproduce**

```r
library(gamma)

tka_test <- system.file("extdata/LaBr.TKA", package = "gamma")
spc_tka <- read(tka_test)

pks <- spc_tka |>
  signal_slice() |>
  signal_stabilize(f = sqrt) |>
  signal_smooth(method = "savitzky", m = 21) |>
  signal_correct(method = "SNIP", decreasing = TRUE, n = 100) |>
  peaks_find()

# Set the energy values (in keV)
set_energy(pks) <- c(238, NA, NA, NA, 1461, NA, NA, 2615)

# Calibrate the energy scale
cal <- energy_calibrate(spc_tka, pks)

# Plot spectrum
plot(cal, pks)
```
![image](https://github.com/user-attachments/assets/c85d0530-5cd7-4323-aca2-e83a81737540)

**Expected behavior**

I would expect that after the peaks are known, the energy peaks are shown correctly:

```r
# Plot spectrum
plot(cal, pks)
```

![image](https://github.com/user-attachments/assets/abaca8e0-0581-4a7b-a861-dad08a8a5638)

**Additional context**

Personally I think that this line: 

https://github.com/crp2a/gamma/blob/33e0d9e1e659de62eafc32ed2d69676f19942426/R/plot.R#L122

Should be modified to: 

```r
peak_energy <- if (all(is.na(pks$energy_expected))) pks$energy_observed else pks$energy_expected
```

This obviously depends on the wanted behaviour, which is not entirely clear to me. I can generate a PR if needed.

**Comment by nfrerebeau** [comment]
I'm trying to remember why we made this choice, but it goes back a long way! I think it was to avoid any ambiguity as to which values were displayed. The "observed" values result solely from the use of `peaks_find()`. This introduces a kind of safeguard, as there is no control over the values passed to `set_energy()`. 

If you think this should be changed, I have no objection in principle. However, it would have to be explicit for the user as to what values are displayed.

**Comment by nfrerebeau** [comment]
I suppose there's no risk in displaying the expected values, as these are the ones used for calibration. In that case, we'd just have to add an additional check to your suggestion:

```
peak_energy <- if (has_calibration(x) && !all(is.na(pks$energy_expected))) pks$energy_expected else pks$energy_observed
```
