### ISSUE TITLE
Enhancement of the import section

### ISSUE THREAD

**Issue by ghost** [crp2a/gamma#6]
In order to improve the user experience here are some feature request for this section : 

- change tab section to : " 1 - file import"
- allow user to display one or more spectra on the plot (tick box ?)

**Comment by nfrerebeau** [comment]
> allow user to display one or more spectra on the plot (tick box ?)

There is already an option in the left panel to select the spectra to be displayed.

**Comment by ghost** [comment]
> > allow user to display one or more spectra on the plot (tick box ?)
> 
> There is already an option in the left panel to select the spectra to be displayed.

Selecting different spectra does not change the plot (see screenshot). Maybe it has something to do with the fact that the plot does not reload ?

![Capture d’écran 2019-11-08 à 13 37 00](https://user-images.githubusercontent.com/49040744/68477138-ed396680-022c-11ea-89ad-274361cac717.png)

**Comment by nfrerebeau** [comment]
You have to remove unwanted spectra from the list. I'll make the label of the select box less ambiguous.
