### ISSUE TITLE
Enhancement of the Dose rate section

### ISSUE THREAD

**Issue by ghost** [crp2a/gamma#8]
In order to improve the user experience here are some feature request for this section :

- Change tab name to : "3 - Dose rate calculation"
- add measurement time value in the table
- add the ability display only selected samples in the table
- add the ability to control the number of significant digits displayed
- add the ability to export the results as .xls

**Comment by nfrerebeau** [comment]
Controlling the number of significant digits displayed could be added as a global setting (not just for the Dose Rate tab) as well as some graphical parameters. We'll see how to fix it later.

xls/xlsx are proprietary formats. The csv format is much more flexible: csv files are plain text, uncompressed and therefore easier to import into a spreadsheet regardless of the software used.

**Comment by ghost** [comment]
> Controlling the number of significant digits displayed could be added as a global setting (not just for the Dose Rate tab) as well as some graphical parameters. We'll see how to fix it later.

To make it easier, perhaps we can consider modifying the export button so that it offers two options:
- export with only X significant digit
- export with all significant digit
